from enum import StrEnum


class AuditAction(StrEnum):
    USER_REGISTERED = "USER_REGISTERED"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILED = "LOGIN_FAILED"
    LOGOUT = "LOGOUT"

    MOVIE_SEARCHED = "MOVIE_SEARCHED"
    MOVIE_VIEWED = "MOVIE_VIEWED"

    MOVIE_ADDED_TO_COLLECTION = "MOVIE_ADDED_TO_COLLECTION"
    MOVIE_REMOVED_FROM_COLLECTION = "MOVIE_REMOVED_FROM_COLLECTION"

    RATING_CREATED = "RATING_CREATED"
    RATING_UPDATED = "RATING_UPDATED"
    RATING_DELETED = "RATING_DELETED"

    AI_SEARCH_REQUESTED = "AI_SEARCH_REQUESTED"
    AI_RECOMMENDATION_REQUESTED = "AI_RECOMMENDATION_REQUESTED"